import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import TRPCProvider from "@/components/providers/trpc-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { ModalProvider } from "@/components/providers/modal-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <TRPCProvider>
          <body className="font-poppins">
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              <ModalProvider />
              <Toaster />
              <Navbar />
              {children}
            </ThemeProvider>
          </body>
        </TRPCProvider>
      </html>
    </ClerkProvider>
  );
}
